--top 5 sale by Quantity..
SELECT pt.name AS pizza_name,
       sum(od.quantity) AS total_sold
FROM order_details od
JOIN pizzas p ON od.pizza_id = p.pizza_id
JOIN pizza_types pt ON p.pizza_type_id = pt.pizza_type_id
GROUP BY pt.name
ORDER BY total_sold
LIMIT 5;


--top revenue generated by pizza..
SELECT pt.name AS pizza_name,
       SUM(od.quantity * p.price) AS total_revenue
FROM order_details od
JOIN pizzas p ON od.pizza_id = p.pizza_id
JOIN pizza_types pt ON p.pizza_type_id = pt.pizza_type_id
GROUP BY pt.name
ORDER BY total_revenue DESC
LIMIT 5;

--Category revenue(top sales).
SELECT pt.category,
       SUM(od.quantity * p.price) AS category_revenue,
       ROUND(
         100 * SUM(od.quantity * p.price) / 
         (SELECT SUM(od2.quantity * p2.price)
          FROM order_details od2
          JOIN pizzas p2 ON od2.pizza_id = p2.pizza_id),
         2
       ) AS percentage_of_total
FROM order_details od
JOIN pizzas p ON od.pizza_id = p.pizza_id
JOIN pizza_types pt ON p.pizza_type_id = pt.pizza_type_id
GROUP BY pt.category
ORDER BY category_revenue DESC;

--Monthly revenue..
SELECT 
    DATE_TRUNC('month', o.order_date) AS month,
    SUM(od.quantity * p.price) AS monthly_revenue
FROM orders o
JOIN order_details od ON o.order_id = od.order_id
JOIN pizzas p ON od.pizza_id = p.pizza_id
GROUP BY DATE_TRUNC('month', o.order_date)
ORDER BY month;

--Most sales of pizza by size..
SELECT 
    p.size,
    SUM(od.quantity) AS total_sold,
    SUM(od.quantity * p.price) AS total_revenue
FROM order_details od
JOIN pizzas p ON od.pizza_id = p.pizza_id
GROUP BY p.size
ORDER BY total_revenue DESC;